apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-office-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: home-office-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: home-office-api
    spec:
      containers:
        - name: home-office-api
          image: marcelormourao/home-office-api:latest
          imagePullPolicy: "IfNotPresent" #"Always"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: home-office-api-cm
            - secretRef:
                name: home-office-secrets

          livenessProbe:
            httpGet:
              path: /home-office-api/user
              port: 8080
              httpHeaders:
              - name: Custom-Header
                value: Awesome
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 60

          readinessProbe:
            httpGet:
              path: /home-office-api/user
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 60
