apiVersion: v1
kind: Service
metadata:
  name: home-office-api
spec:
  type: NodePort
  selector:
    app: home-office-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30030
      